name: Continuous Integration

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['**']

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and Test
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn test

      - name: Build
        run: yarn build
